name: test
on:
  push: {}
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@master
        with:
          key: v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          path: |
            node_modules
      - run: yarn install
      - run: yarn tsc
      - run: yarn test

